version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.api/Dockerfile
    ports:
    - "5000:8080"
    - "5001:5001"
    networks:
    - "proxybackend"

  followers.api:
    image: ${DOCKER_REGISTRY-}followersapi
    build:
      context: .
      dockerfile: Followers.api/Dockerfile
    ports:
    - "5200:8080"
    - "5201:5201"
    networks:
    - "proxybackend"

  tweets.api:
    image: ${DOCKER_REGISTRY-}tweetsapi
    build:
      context: .
      dockerfile: Tweets.api/Dockerfile
    ports:
    - "5100:8080"
    - "5101:5101"
    networks:
    - "proxybackend"

  users.api:
      image: ${DOCKER_REGISTRY-}usersapi
      build:
         context: .
         dockerfile: Users.api/Dockerfile
      ports:
      - "5300:8080"
      - "5301:5301"
      networks:
      - "proxybackend"

  notifications.api:
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: Notifications.api/Dockerfile
    ports:
      - "5400:8080"
      - "5401:5401"
    networks:
    - "proxybackend"
  
  tweets.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: tweets_database
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_ENCRYPT: "0" 
    ports:
      - "1433:1433"
    volumes:
       - tweets_data:/var/opt/mssql
    networks:
    - "proxybackend"

  users.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: users_database
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
    - users_data:/var/opt/mssql
    networks:
    - "proxybackend"

  followers.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: followers_database
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
    - followers_data:/var/opt/mssql
    networks:
    - "proxybackend"

volumes:
  tweets_data:
    driver: local
  users_data:
    driver: local
  followers_data:
    driver: local
    
networks:
  proxybackend:
    name: proxybackend
    driver: bridge
