version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.api/Dockerfile
    ports:
    - "5000:8080"
    - "5001:5001"
    networks:
    - "proxybackend"

  followers.api:
    image: ${DOCKER_REGISTRY-}followersapi
    build:
      context: .
      dockerfile: Followers.api/Dockerfile
    ports:
    - "5200:8080"
    - "5201:5201"
    networks:
    - "proxybackend"


  tweets.api:
    image: ${DOCKER_REGISTRY-}tweetsapi
    build:
      context: .
      dockerfile: Tweets.api/Dockerfile
    ports:
    - "5100:8080"
    - "5101:5101"
    networks:
    - "proxybackend"



networks:
    proxybackend:
     name: proxybackend
     driver: bridge