apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: accountsapi
  name: accountsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accountsapi
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: accountsapi
    spec:
      containers:
        - image: accountsapi
          name: accountsapi
          ports:
            - containerPort: 8080
              hostPort: 5500
              protocol: TCP
      restartPolicy: Always
