apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: accountsapi
  name: accountsapi
spec:
  ports:
    - name: "5500"
      port: 5500
      targetPort: 8080
    - name: "5501"
      port: 5501
      targetPort: 5501
  selector:
    io.kompose.service: accountsapi
