apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: followersdatabase
  name: followersdatabase
spec:
  ports:
    - name: "1435"
      port: 1435
      targetPort: 1433
  selector:
    io.kompose.service: followersdatabase
