apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: followersapi
  name: followersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: followersapi
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: followersapi
    spec:
      containers:
        - image: followersapi
          name: followersapi
          ports:
            - containerPort: 8080
              hostPort: 5200
              protocol: TCP
            - containerPort: 5201
              hostPort: 5201
              protocol: TCP
      restartPolicy: Always
