apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: followers-api
  name: followers-api
spec:
  ports:
    - name: "5200"
      port: 5200
      targetPort: 8080
    - name: "5201"
      port: 5201
      targetPort: 5201
  selector:
    io.kompose.service: followers-api
