apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: gateway-api
  name: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: gateway-api
    spec:
      containers:
        - image: ginotoch/gateway:latest
          name: gateway-api
          ports:
            - containerPort: 8080
              hostPort: 9000
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: gateway-api-config
            items:
              - key: appsettings.yaml
                path: appsettings.yaml
