apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gatewayapi-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gatewayapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
