apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: gatewayapi
  name: gatewayapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatewayapi
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: gatewayapi
    spec:
      containers:
        - image: ginotoch/gateway:latest
          name: gatewayapi
          ports:
            - containerPort: 8080
              hostPort: 9000
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: configmap
            items:
              - key: appsettings.yaml
                path: appsettings.yaml
