apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: gatewayapi
  name: gatewayapi
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: gatewayapi
