apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: kwetter-mq
  name: kwetter-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kwetter-mq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: kwetter-mq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: rabbitmq:management
          name: kwetter.rabbitmq
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
            - containerPort: 15672
              hostPort: 15672
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: kwetter-mq-cm0
            - mountPath: /var/log/rabbitmq
              name: kwetter-mq-claim1
      hostname: kwetter-mq
      restartPolicy: Always
      volumes:
        - configMap:
            name: kwetter-mq-cm0
          name: kwetter-mq-cm0
        - name: kwetter-mq-claim1
          persistentVolumeClaim:
            claimName: kwetter-mq-claim1
