apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: notifications-api
  name: notifications-api
spec:
  ports:
    - name: "5400"
      port: 5400
      targetPort: 8080
    - name: "5401"
      port: 5401
      targetPort: 5401
  selector:
    io.kompose.service: notifications-api
