apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: tweets-api
  name: tweets-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tweets-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: tweets-api
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tweetsapi.dashboard:18889
          image: tweetsapi
          name: tweets-api
          ports:
            - containerPort: 8080
              hostPort: 5100
              protocol: TCP
            - containerPort: 5101
              hostPort: 5101
              protocol: TCP
      restartPolicy: Always
