apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: tweetsapi
  name: tweetsapi
spec:
  ports:
    - name: "5100"
      port: 5100
      targetPort: 8080
    - name: "5101"
      port: 5101
      targetPort: 5101
  selector:
    io.kompose.service: tweetsapi
