apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: tweetsapi
  name: tweetsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tweetsapi
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o Kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/proxybackend: "true"
        io.kompose.service: tweetsapi
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tweetsapi.dashboard:18889
          image: ginotoch/tweetservice:latest
          name: tweetsapi
          ports:
            - containerPort: 5300
              protocol: TCP
          env:
            - name: ConnectionStrings__Database
              value: "Server=tcp:kwetterserver.database.windows.net,1433;Initial Catalog=tweetdatabase;Persist Security Info=False;User ID=kwetteradmin;Password=adminkwetter!1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
      restartPolicy: Always
