apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: usersapi-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usersapi
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
