name: Cypress Tests
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened ]
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        working-directory: ./Frontend

      # - name: Install wait-on
      #   run: npm install -g wait-on
        
      - name: Start server
        run: |
          echo "Starting server..."
          npm run preview >server-log.txt 2>&1 &
          echo "Server started in the background"
        working-directory: ./Frontend


      - name: Run Cypress tests
        run: |
          echo "Running Cypress tests..."
          npx cypress run --record --parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./Frontend

      - name: Upload server log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: server-log
          path: ./Frontend/server-log.txt
