name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify .NET 8

    - name: Restore dependencies
      run: |
        cd Backend/Services/Kwetter  # Navigate to the directory containing Kwetter.sln
        dotnet restore Kwetter.sln
      # Adjust the path to your solution file (Kwetter.sln) and navigate to its directory

    - name: Build solution
      run: |
        cd Backend/Services/Kwetter  # Navigate to the directory containing Kwetter.sln
        dotnet build Kwetter.sln --no-restore
      # Adjust the path to your solution file (Kwetter.sln) and navigate to its directory

    - name: Run integration tests
      run: |
        cd Backend/Services/Kwetter  # Navigate to the directory containing Kwetter.sln
        dotnet test Backend/Services/Kwetter/KwetterIntegrationTestsUsers --no-build --logger trx
      # Adjust the path to your test project directory and navigate to its directory
