name: Run integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Backend/Services/Kwetter/Kwetter.sln
      working-directory: Backend/Services/Kwetter
      # Adjust the path to your solution file and set the working directory accordingly

    - name: Build solution
      run: dotnet build Backend/Services/Kwetter/Kwetter.sln --no-restore
      working-directory: Backend/Services/Kwetter
      # Adjust the path to your solution file and set the working directory accordingly

    - name: Run integration tests
      run: dotnet test Backend/Services/Kwetter/KwetterIntegrationTestsUsers --no-build --logger trx
      working-directory: Backend/Services/Kwetter
      # Adjust the path to your test project directory and set the working directory accordingly
