name: Integration Tests

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Adjust to '6.x' if using .NET 6

      - name: Restore dependencies
        run: |
          cd Backend/Services/Kwetter 
          dotnet restore Kwetter.sln

      - name: Build
        run: |
          cd Backend/Services/Kwetter
          dotnet build Kwetter.sln

      - name: Change directory to Backend/Services/Kwetter
        run: cd Backend/Services/Kwetter/KwetterIntegrationTestsUsers

      - name: Run integration tests
        run: |
          dotnet test KwetterIntegrationTestsUsers.csproj
