name: Sast CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download SAST script
        run: curl -s -o betterscan.sh https://dl.betterscan.io/cli.sh
        
      - name: Execute SAST script
        run: sh betterscan.sh
